url: "https://adamwattis.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "Adam Wattis" # the name of your site, e.g. ACME Corp.
description: > # this means to ignore newlines until "baseurl:"
  Adam Wattis - developer portfolio. Building projects from scratch using technologies 
  such as React Native and JavaScript.
baseurl: "" # the subpath of your site, e.g. /blog
